title: "Your Cybersecurity Blog"
description: "Technical writeups and research"

url: "https://d-typing.github.io"
baseurl: "/BlogSite"

theme: minima
markdown: kramdown
highlighter: rouge

collections:
  projects:
    output: true
    permalink: /projects/:name/

  writeups:
    output: true
    layout: writeup
    permalink: /writeups/:name/
